site_name: Bambusrollstuhl â€“ Bauanleitung
site_description: Open-Source Bauanleitung & Community-Builds
site_url: https://Bamboobility.github.io/   # bei Project Pages
repo_url: https://github.com/Bamboobility
repo_name: Bamboobility/Bamboobility

theme:
  name: material
  language: de
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Start: index.md
  - Anleitung: instructions.md
  - Downloads: downloads.md
  - Community:
      - GitHub Discussions: https://github.com/Bamboobility/Bamboobility.github.io/discussions

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search
